### ISSUE TITLE
how to implement a similar package but with yolov5?

### ISSUE THREAD

**Issue by haniaraslan** [Setrexis/yolov4tflite#1]
hello, i'm trying to implement a similar package but for yolov5, is there any references that can help me?

**Comment by Setrexis** [comment]
Hey, 
I mostly build the android part of this package upon the java implementation of this repo https://github.com/hunglc007/tensorflow-yolov4-tflite which is built upon Tensorflows example yolov4 implementations.
The ios part was also inspired by the Tensorflow swift example implementation of yolov4.
I hope this helps you a bit.
